name: ios build

on:
    push:
    pull_request:
        
jobs:
    build:
        name: ios build
        runs-on: macos-latest
        
        steps:
            - name: checkout repo
              uses: actions/checkout@main
              
            - name: install include tools
              run: |
                brew install make
              
            - name: build for ios
              run: |
                ./configure --host=aarch64-apple-ios CC="clang -arch arm64"
                make
                ls

            - name: upload dylib
              uses: actions/upload-artifact@main
              with:
                name: libsqlite3
                path: ./libsqlite3.dylib

            - name: upload dylib
              uses: actions/upload-artifact@main
              with:
                name: libsqlite3
                path: ./libsqlite3.so
                